services:
  tts-server:
    image: mercenary9312/tts-server
    build: .
    container_name: tts-server
    ports:
      - "3000:3000"
    volumes:
      - ./output:/app/output
    restart: unless-stopped